# Generated by Django 4.2.11 on 2024-03-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='is_expeditor',
            field=models.BooleanField(default=False, editable=False, verbose_name='Является экспедитором'),
        ),
    ]
