# Generated by Django 4.2.11 on 2024-03-30 14:46

import cats.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_organisation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'параметр груза',
                'verbose_name_plural': 'параметры груза',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True, verbose_name='Код валюты')),
                ('displayed_name', models.CharField(max_length=10, unique=True, verbose_name='Отображаемое имя')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'тип упаковки',
                'verbose_name_plural': 'типы упаковки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('name',), 'verbose_name': 'организация', 'verbose_name_plural': 'организации'},
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('expiry_date', models.DateField(verbose_name='Дата окончания действия')),
                ('currency', models.ForeignKey(default=cats.models.Currency.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='cats.currency', verbose_name='Валюта')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.organisation', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'договор',
                'verbose_name_plural': 'договоры',
                'ordering': ('date', 'number'),
                'unique_together': {('organization', 'number')},
            },
        ),
    ]
