# Generated by Django 4.2.11 on 2024-03-30 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import logistics.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        ('cats', '0001_initial'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('number', models.CharField(db_index=True, default=logistics.models.default_order_number, max_length=5, unique=True, validators=[logistics.models.int_only_validator], verbose_name='Номер заявки')),
                ('client_number', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Клиентский номер')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('gov_contract_number', models.CharField(blank=True, max_length=255, verbose_name='№ ИГК')),
                ('cargo_name', models.CharField(max_length=255, verbose_name='Наименование груза')),
                ('cargo_value', models.FloatField(verbose_name='Заявленная стоимость груза')),
                ('insurance_needed', models.BooleanField(default=False, verbose_name='Страхование требуется')),
                ('insurance_premium', models.FloatField(blank=True, default=0, verbose_name='Страховая премия')),
                ('insurance_sum_rate', models.FloatField(choices=[(1, '100%'), (1.1, '110%')], default=1, verbose_name='Коэффициент страховой суммы')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Ставка')),
                ('from_contacts', models.TextField(verbose_name='Контакты грузоотправителя')),
                ('from_index', models.IntegerField(verbose_name='Индекс пункта отправки')),
                ('from_address', models.CharField(max_length=255, verbose_name='Адрес отправки')),
                ('from_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название пункта отправки')),
                ('from_date_wanted', models.DateField(blank=True, null=True, verbose_name='Дата готовности груза')),
                ('from_date_plan', models.DateField(blank=True, null=True, verbose_name='Дата отправки (план)')),
                ('from_date_fact', models.DateField(blank=True, null=True, verbose_name='Дата отправки (факт)')),
                ('to_contacts', models.TextField(verbose_name='Контакты грузополучателя')),
                ('to_index', models.IntegerField(verbose_name='Индекс пункта доставки')),
                ('to_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('to_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название пункта доставки')),
                ('to_date_wanted', models.DateField(blank=True, null=True, verbose_name='Желаемая дата доставки')),
                ('to_date_plan', models.DateField(blank=True, null=True, verbose_name='Дата доставки (план)')),
                ('to_date_fact', models.DateField(blank=True, null=True, verbose_name='Дата доставки (факт)')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('prepare', 'Подготовка к перевозке'), ('in_progress', 'В пути'), ('delivered', 'Доставлено'), ('docs_received', 'Документы получены'), ('complete', 'Завершено')], default='new', max_length=25, verbose_name='Статус')),
                ('tracking_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на отслеживание')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('service_marks', models.TextField(blank=True, null=True, verbose_name='Служебные отметки')),
                ('sum_weight', models.FloatField(blank=True, null=True, verbose_name='Суммарный вес брутто, кг')),
                ('sum_volume', models.FloatField(blank=True, null=True, verbose_name='Суммарный объем груза, м3')),
                ('sum_quantity', models.IntegerField(blank=True, null=True, verbose_name='Суммарное кол-во мест')),
                ('cargo_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_origin_in_orders', to='geo.country', verbose_name='Страна происхождения груза')),
                ('cargo_value_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_value_currency_in_orders', to='cats.currency', verbose_name='Валюта стоимости груза')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_in_orders', to='orgs.organisation', verbose_name='Заказчик')),
                ('client_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_employee_in_orders', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник заказчика')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_in_orders', to='orgs.contract', verbose_name='Договор')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_city_in_orders', to='geo.city', verbose_name='Город отправки')),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_country_in_orders', to='geo.country', verbose_name='Страна отправки')),
                ('from_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_org_in_orders', to='orgs.organisation', verbose_name='Грузоотправитель')),
                ('insurance_beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary_in_orders', to='orgs.organisation', verbose_name='Выгодоприобретатель')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_in_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('price_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_currency_in_orders', to='cats.currency', verbose_name='Валюта ставки')),
                ('services', models.ManyToManyField(to='cats.service', verbose_name='Доп. услуги')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_city_in_orders', to='geo.city', verbose_name='Город доставки')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_country_in_orders', to='geo.country', verbose_name='Страна доставки')),
                ('to_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_org_in_orders', to='orgs.organisation', verbose_name='Грузополучатель')),
            ],
            options={
                'verbose_name': 'заявка на перевозку',
                'verbose_name_plural': 'заявки на перевозку',
                'ordering': ('number', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('mark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Маркировка')),
                ('length', models.FloatField(verbose_name='Длина, см')),
                ('width', models.FloatField(verbose_name='Ширина, см')),
                ('height', models.FloatField(verbose_name='Высота, см')),
                ('weight', models.FloatField(verbose_name='Вес одного места, кг')),
                ('quantity', models.IntegerField(verbose_name='Количество мест')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='logistics.order', verbose_name='Заявка')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cats.package', verbose_name='Тип упаковки')),
                ('params', models.ManyToManyField(to='cats.cargoparam', verbose_name='Доп. параметры груза')),
            ],
            options={
                'verbose_name': 'груз',
                'verbose_name_plural': 'грузы',
                'ordering': ('created_at',),
            },
        ),
    ]
