# Generated by Django 4.2.11 on 2024-03-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='params',
            field=models.ManyToManyField(blank=True, to='cats.cargoparam', verbose_name='Доп. параметры груза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, to='cats.service', verbose_name='Доп. услуги'),
        ),
    ]
