# Generated by Django 4.2.11 on 2024-03-31 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_cargo_params_alter_order_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='quantity',
            field=models.IntegerField(verbose_name='Кол-во мест'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.FloatField(verbose_name='Вес, кг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во мест'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем груза, м3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес брутто груза, кг'),
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(choices=[('new', 'Новая'), ('prepare', 'Подготовка к перевозке'), ('in_progress', 'В пути'), ('delivered', 'Доставлено'), ('docs_received', 'Документы получены'), ('complete', 'Завершено')], default='new', max_length=25, verbose_name='Статус')),
                ('change_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время изменения статуса')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'статус заявки',
                'verbose_name_plural': 'статусы заявки',
                'ordering': ('-change_time',),
            },
        ),
    ]
