# Generated by Django 4.2.11 on 2024-03-31 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_cargo_quantity_alter_cargo_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ('order', '-change_time'), 'verbose_name': 'статус заявки', 'verbose_name_plural': 'статусы заявки'},
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='change_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время изменения статуса'),
        ),
    ]
