# Generated by Django 4.2.11 on 2024-03-31 13:30

from django.db import migrations, models
import django.db.models.deletion
import logistics.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_remove_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to=logistics.models.path_by_order, verbose_name='Файл')),
                ('is_public', models.BooleanField(db_index=True, default=False, verbose_name='Показать клиенту')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Приложенный файл',
                'verbose_name_plural': 'Приложенные файлы',
                'ordering': ('-created_at',),
            },
        ),
    ]
