# Generated by Django 4.2.11 on 2024-04-22 17:23

import cats.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
        ('logistics', '0006_attacheddocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-number', '-created_at'), 'verbose_name': 'заявка на перевозку', 'verbose_name_plural': 'заявки на перевозку'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('prepare', 'Подготовка к перевозке'), ('in_progress', 'В пути'), ('delivered', 'Доставлено'), ('docs_received', 'Документы получены'), ('complete', 'Завершено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_updated',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время изменения статуса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_value_currency',
            field=models.ForeignKey(default=cats.models.Currency.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_value_currency_in_orders', to='cats.currency', verbose_name='Валюта стоимости груза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_currency',
            field=models.ForeignKey(default=cats.models.Currency.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='price_currency_in_orders', to='cats.currency', verbose_name='Валюта ставки'),
        ),
    ]
