# Generated by Django 4.2.11 on 2024-06-05 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_order_options_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Высота, см'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='length',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во мест'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес, кг'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='width',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина, см'),
        ),
    ]
