# Generated by Django 4.2.11 on 2024-06-12 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import logistics.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0001_initial'),
        ('logistics', '0009_attacheddocument_allow_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('number', models.CharField(db_index=True, default=logistics.models.default_quick_order_number, max_length=5, unique=True, validators=[logistics.models.int_only_validator], verbose_name='Номер заявки')),
                ('client_number', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Клиентский номер')),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quick_orders', to='orgs.organisation', verbose_name='Заказчик')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='quick_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки')),
            ],
            options={
                'verbose_name': 'быстрая заявка',
                'verbose_name_plural': 'быстрые заявки',
                'ordering': ('-number', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='QuickAttachedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to=logistics.models.path_by_order, verbose_name='Файл')),
                ('quick_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.quickorder', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Приложенный файл',
                'verbose_name_plural': 'Приложенные файлы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='quick_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.quickorder', verbose_name='Быстрая заявка'),
        ),
    ]
