# Generated by Django 4.2.11 on 2024-06-12 16:27

from django.db import migrations, models
import logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_quickorder_quickattacheddocument_order_quick_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickattacheddocument',
            name='file',
            field=models.FileField(upload_to=logistics.models.path_by_quick_order, verbose_name='Файл'),
        ),
    ]
