# Generated by Django 4.2.11 on 2024-06-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_quickattacheddocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Индекс пункта отправки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Индекс пункта доставки'),
        ),
    ]
