# Generated by Django 4.2.11 on 2024-06-14 10:41

from django.db import migrations, models
import django.db.models.deletion
import geo.models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_city_options_alter_city_name_and_more'),
        ('logistics', '0012_alter_order_from_index_alter_order_to_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_country',
            field=models.ForeignKey(default=geo.models.Country.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='from_country_in_orders', to='geo.country', verbose_name='Страна отправки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_country',
            field=models.ForeignKey(default=geo.models.Country.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='to_country_in_orders', to='geo.country', verbose_name='Страна доставки'),
        ),
    ]
