# Generated by Django 4.2.11 on 2024-03-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
